import type { Application, EmailAlert, ResumeProfile } from './types'

function fixedDate(month: number, day: number, hour = 9, minute = 0) {
  return new Date(2026, month - 1, day, hour, minute).toISOString()
}

function agoFromNow({
  days = 0,
  hours = 0,
}: {
  days?: number
  hours?: number
}) {
  return new Date(Date.now() - ((days * 24 + hours) * 60 * 60 * 1000)).toISOString()
}

export const mockApplications: Application[] = [
  {
    id: 'app-1',
    company: '美团',
    position: 'AI产品经理',
    link: 'https://zhaopin.meituan.com/web/position/detail?jobUnionId=4220518746&highlightType=campus',
    currentStage: '一面',
    stageMeta: {
      interview1Time: fixedDate(4, 20, 15, 0),
    },
    jdNote: '偏 AI 产品设计与业务落地，需要理解大模型能力边界、用户场景拆解和功能方案输出。',
    resumeVersion: '产品经理版 V3',
    createdAt: agoFromNow({ days: 5 }),
    updatedAt: agoFromNow({ hours: 8 }),
  },
  {
    id: 'app-2',
    company: '腾讯',
    position: '行业运营实习',
    link: 'https://join.qq.com/post_detail.html?postid=1153452731391100931',
    currentStage: '已投递',
    stageMeta: {},
    jdNote: '偏行业运营与策略支持，需要关注行业研究、项目推进和跨团队协作。',
    resumeVersion: '运营策略版 V1',
    createdAt: agoFromNow({ days: 9 }),
    updatedAt: agoFromNow({ days: 6 }),
  },
  {
    id: 'app-3',
    company: '字节跳动',
    position: '数据产品实习生-数据平台',
    link: 'https://jobs.bytedance.com/campus/position/7591800608638765365/detail',
    currentStage: '测评中',
    stageMeta: {
      assessmentDeadline: fixedDate(4, 21, 18, 0),
    },
    jdNote: '聚焦数据平台产品能力建设，需要理解埋点、指标体系、数据链路和平台化能力设计。',
    resumeVersion: '数据产品版 V4',
    createdAt: agoFromNow({ days: 4, hours: 6 }),
    updatedAt: agoFromNow({ hours: 3 }),
  },
  {
    id: 'app-4',
    company: '阿里巴巴',
    position: 'AI产品经理-超级智能体',
    link: 'https://campus-talent.alibaba.com/campus/position/199903780010?deptCodes=',
    currentStage: '笔试1',
    stageMeta: {
      test1Time: fixedDate(4, 23, 19, 0),
      test1Deadline: fixedDate(4, 23, 22, 0),
    },
    jdNote: '关注智能体交互、任务规划和产品落地能力，可能会考察 AI 方向认知和产品案例分析。',
    resumeVersion: 'AI 产品版 V2',
    createdAt: agoFromNow({ days: 7 }),
    updatedAt: agoFromNow({ hours: 5 }),
  },
  {
    id: 'app-5',
    company: '小红书',
    position: '点点策略产品实习生',
    link: 'https://job.xiaohongshu.com/campus/position/18781',
    currentStage: '二面',
    stageMeta: {
      interview2Time: fixedDate(4, 24, 14, 30),
    },
    jdNote: '偏策略产品与增长实验，需要较强的数据敏感度、分析框架和需求抽象能力。',
    resumeVersion: '产品经理版 V3',
    createdAt: agoFromNow({ days: 8 }),
    updatedAt: agoFromNow({ hours: 10 }),
  },
  {
    id: 'app-6',
    company: '京东',
    position: '物流产品规划',
    link: 'https://campus.jd.com/#/details?id=4920',
    currentStage: '笔试2',
    stageMeta: {
      test2Time: fixedDate(4, 25, 10, 0),
      test2Deadline: fixedDate(4, 25, 18, 0),
    },
    jdNote: '岗位偏物流场景产品规划，强调流程理解、复杂业务抽象和结构化表达。',
    resumeVersion: '产品经理版 V3',
    createdAt: agoFromNow({ days: 11 }),
    updatedAt: agoFromNow({ days: 1, hours: 4 }),
  },
  {
    id: 'app-7',
    company: '携程',
    position: '数据分析实习生',
    link: 'https://www.shixiseng.com/intern/inn_noy005ji4xnh',
    currentStage: 'Offer',
    stageMeta: {
      offerConfirmTime: fixedDate(4, 26, 18, 0),
    },
    jdNote: '偏业务分析与经营洞察，需要 SQL、报表搭建和基础统计分析能力。',
    resumeVersion: '数据分析版 V2',
    createdAt: agoFromNow({ days: 16 }),
    updatedAt: agoFromNow({ hours: 18 }),
  },
  {
    id: 'app-8',
    company: '快手',
    position: '数据产品实习生-【商业化】',
    link: 'https://www.shixiseng.com/intern/inn_tonep3jnerxs',
    currentStage: '已淘汰',
    stageMeta: {},
    jdNote: '商业化数据产品方向，关注变现链路、指标分析和中台产品能力，已在笔试后止步。',
    resumeVersion: '数据产品版 V4',
    createdAt: agoFromNow({ days: 18 }),
    updatedAt: agoFromNow({ days: 2 }),
  },
  {
    id: 'app-9',
    company: '招商银行',
    position: '金融数字训练营',
    link: 'https://career.cmbchina.com/positionDetail/school?publishId=D0DC5A9A-888B-4134-95FF-1EEAC80EB4F5',
    currentStage: '待投递',
    stageMeta: {
      applyDeadline: fixedDate(4, 21, 23, 59),
    },
    jdNote: '金融科技与数字化方向训练营，可能涉及轮岗培养、金融产品认知与数据分析基础。',
    resumeVersion: '金融求职版 V1',
    createdAt: agoFromNow({ days: 1 }),
    updatedAt: agoFromNow({ hours: 6 }),
  },
  {
    id: 'app-10',
    company: '中金公司',
    position: '研究助理',
    link: 'https://cicc.zhiye.com/personal/deliveryRecord',
    currentStage: 'HR面',
    stageMeta: {
      hrInterviewTime: fixedDate(4, 28, 15, 0),
    },
    jdNote: '偏研究支持与资料整理，重视行业研究基础、信息检索能力和严谨表达。',
    resumeVersion: '研究助理版 V1',
    createdAt: agoFromNow({ days: 13 }),
    updatedAt: agoFromNow({ days: 1, hours: 2 }),
  },
  {
    id: 'app-11',
    company: '网易',
    position: '平台产品经理',
    link: 'https://www.shixiseng.com/intern/inn_i2pqhdd80wet',
    currentStage: '已通过',
    stageMeta: {},
    jdNote: '偏平台类产品岗位，已完成流程，可作为平台能力题和项目表达的复盘样本。',
    resumeVersion: '产品经理版 V3',
    createdAt: agoFromNow({ days: 24 }),
    updatedAt: agoFromNow({ days: 5 }),
  },
  {
    id: 'app-12',
    company: '滴滴',
    position: '数据运营实习生',
    link: 'https://www.shixiseng.com/intern/inn_jxy2lhnc9dnn',
    currentStage: '背调中',
    stageMeta: {
      bgCheckDeadline: fixedDate(4, 29, 18, 0),
    },
    jdNote: '偏数据运营和业务分析，需要支持经营复盘、策略迭代和日常指标监控。',
    resumeVersion: '数据分析版 V2',
    createdAt: agoFromNow({ days: 19 }),
    updatedAt: agoFromNow({ hours: 14 }),
  },
  {
    id: 'app-13',
    company: '蔚来',
    position: '运营实习生',
    link: 'https://www.shixiseng.com/intern/inn_k5wcwrfx3svi',
    currentStage: '一面',
    stageMeta: {
      interview1Time: fixedDate(4, 16, 14, 0),
    },
    jdNote: '偏项目运营推进、培训与活动支持，需要较强沟通协调、数据整理和文案能力。',
    resumeVersion: '运营策略版 V1',
    createdAt: agoFromNow({ days: 6 }),
    updatedAt: agoFromNow({ days: 1, hours: 5 }),
  },
]

export const mockEmails: EmailAlert[] = [
  {
    id: 'mail-1',
    from: 'campus@meituan.com',
    companyHint: '美团',
    subject: '【美团】AI产品经理一面安排',
    snippet: '请于 4 月 20 日 15:00 参加视频一面，并提前 10 分钟进入会议室。',
    receivedAt: agoFromNow({ hours: 4 }),
    isRead: true,
  },
  {
    id: 'mail-2',
    from: 'talent@bytedance.com',
    companyHint: '字节跳动',
    subject: '数据产品实习生测评截止提醒',
    snippet: '请在 4 月 21 日 18:00 前完成在线测评，逾期系统将自动关闭入口。',
    receivedAt: agoFromNow({ hours: 7 }),
    isRead: true,
  },
  {
    id: 'mail-3',
    from: 'campus@alibaba-inc.com',
    companyHint: '阿里巴巴',
    subject: 'AI产品经理笔试通知',
    snippet: '笔试将于 4 月 23 日晚开启，请在当日 22:00 前完成全部题目提交。',
    receivedAt: agoFromNow({ hours: 12 }),
    isRead: true,
  },
  {
    id: 'mail-4',
    from: 'campus@xiaohongshu.com',
    companyHint: '小红书',
    subject: '点点策略产品实习生二面邀请',
    snippet: '二面安排在 4 月 24 日 14:30，请准备一段项目复盘和策略分析案例。',
    receivedAt: agoFromNow({ hours: 20 }),
    isRead: true,
  },
  {
    id: 'mail-5',
    from: 'campus@jd.com',
    companyHint: '京东',
    subject: '物流产品规划笔试 2 轮安排',
    snippet: '第二轮在线笔试时间已确认，请于 4 月 25 日 18:00 前完成作答。',
    receivedAt: agoFromNow({ days: 1, hours: 3 }),
    isRead: true,
  },
  {
    id: 'mail-6',
    from: 'recruiting@ctrip.com',
    companyHint: '携程',
    subject: 'Offer 发放及确认说明',
    snippet: '恭喜你通过全部流程，请在 4 月 26 日 18:00 前确认是否接受 Offer。',
    receivedAt: agoFromNow({ days: 1, hours: 1 }),
    isRead: true,
  },
  {
    id: 'mail-7',
    from: 'campus@cmbchina.com',
    companyHint: '招商银行',
    subject: '金融数字训练营投递截止提醒',
    snippet: '请在 4 月 21 日 23:59 前完成投递与附件上传，逾期将无法补交。',
    receivedAt: agoFromNow({ days: 1, hours: 4 }),
    isRead: true,
  },
  {
    id: 'mail-8',
    from: 'recruiting@cicc.com.cn',
    companyHint: '中金公司',
    subject: '研究助理 HR 面安排',
    snippet: 'HR 面拟安排在 4 月 28 日 15:00，若时间冲突请于 24 小时内邮件回复协调。',
    receivedAt: agoFromNow({ days: 2, hours: 2 }),
    isRead: true,
  },
  {
    id: 'mail-9',
    from: 'talent@didiglobal.com',
    companyHint: '滴滴',
    subject: '背调材料补充提醒',
    snippet: '请在 4 月 29 日 18:00 前补充学籍证明和实习协议信息，以便完成背调。',
    receivedAt: agoFromNow({ hours: 15 }),
    isRead: true,
  },
  {
    id: 'mail-10',
    from: 'campus.nio.com',
    companyHint: '蔚来',
    subject: '运营实习生流程更新提醒',
    snippet: '你的面试流程状态已更新，请登录系统查看最新结果。',
    receivedAt: agoFromNow({ hours: 2 }),
    isRead: false,
  },
]

export const mockResumes: ResumeProfile[] = [
  {
    id: 'resume-1',
    name: '产品经理版 V3',
    category: '产品',
    usedCount: 5,
    lastUsed: agoFromNow({ days: 1 }),
  },
  {
    id: 'resume-2',
    name: '数据分析版 V2',
    category: '数据',
    usedCount: 3,
    lastUsed: agoFromNow({ days: 3 }),
  },
  {
    id: 'resume-3',
    name: '运营策略版 V1',
    category: '运营',
    usedCount: 2,
    lastUsed: agoFromNow({ hours: 8 }),
  },
  {
    id: 'resume-4',
    name: '数据产品版 V4',
    category: '产品',
    usedCount: 2,
    lastUsed: agoFromNow({ days: 2 }),
  },
  {
    id: 'resume-5',
    name: 'AI 产品版 V2',
    category: '产品',
    usedCount: 1,
    lastUsed: agoFromNow({ days: 4 }),
  },
  {
    id: 'resume-6',
    name: '金融求职版 V1',
    category: '金融',
    usedCount: 1,
    lastUsed: agoFromNow({ days: 1, hours: 6 }),
  },
  {
    id: 'resume-7',
    name: '研究助理版 V1',
    category: '研究',
    usedCount: 1,
    lastUsed: agoFromNow({ days: 2, hours: 4 }),
  },
]
